#!/bin/sh

main() {
    parse_opts "$@"

    { [ -n "$help" ] && help; } ||
    { [ -n "$governor" ] && governor; } ||
    { [ -n "$freq" ] && frequency; } ||
    { [ -n "$minfreq" ] && minimum_frequency; } ||
    { [ -n "$maxfreq" ] && maximum_frequency; } ||
    { menu; } 
}

menu() {
    cmd="$(printf 'governor\nfrequency\nminimum frequency\nmaximum frequency' | dmenu -i -p 'DCPU')"

    { [ "$cmd" = "governor" ] && governor; } ||
    { [ "$cmd" = "frequency" ] && frequency; } ||
    { [ "$cmd" = "minimum frequency" ] && minimum_frequency; } ||
    { [ "$cmd" = "maximum frequency" ] && maximum_frequency; }
}

governor() {
    cpupower frequency-info | grep "available cpufreq governors: " | awk -F "available cpufreq governors: " {'print $2'} | tr ' ' '\n' | dmenu -p "governor" | xargs -I {} doas_askpass cpupower -c all frequency-set --governor "{}"
}

frequency() {
    cpupower frequency-info | grep "frequency should be within " | awk -F "frequency should be within " {'print $2'} | rev | tr -s " " | cut -d "." -f 2- | rev | sed 's/ and /\n/g' | dmenu -p "frequency" | tr -d ' ' | xargs -I {} doas_askpass cpupower -c all frequency-set --freq "{}"
}

minimum_frequency() {
    cpupower frequency-info | grep "frequency should be within " | awk -F "frequency should be within " {'print $2'} | rev | tr -s " " | cut -d "." -f 2- | rev | sed 's/ and /\n/g' | dmenu -p "minimum frequency" | xargs -I {} doas_askpass cuppower -c all frequency-set --min "{}"
}

maximum_frequency() {
    cpupower frequency-info | grep "frequency should be within " | awk -F "frequency should be within " {'print $2'} | rev | tr -s " " | cut -d "." -f 2- | rev | sed 's/ and /\n/g' | dmenu -p "minimum frequency" | xargs -I {} doas_askpass cuppower -c all frequency-set --max "{}"
}

help() {
    printf "Usage:	dcpu [option]

Options:
 -g|--governor │ Manage governor
 -f|--freq     │ Manage frequency
-fl|--minfreq  │ Manage minimum frequency
-fh|--maxfreq  │ Manage maximum frequency
 -h|--help     │ Print this help message and exit
When no arguments are supplied, the default menu will be used.
\n"
}

parse_opts() {
    while [ $# -gt 0 ]; do
        key="$1"
        case $key in
        -h|--help)
            help=1
            shift
            ;;
	-g|--governor)
	    governor=1
	    shift
	    ;;
	-f|--freq)
	    freq=1
	    shift
	    ;;
	-fl|--minfreq)
	    minfreq=1
	    shift
	    ;;
	-fh|--maxfreq)
	    maxfreq=1
	    shift
	    ;;
	*)
	    shift
	    ;;
	esac
    done
}

main "$@"
