#!/bin/sh

main() {
    parse_opts "$@"

    { [ -n "$help" ] && help; } ||
    { [ -n "$governor" ] && governor; } ||
    { [ -n "$minfreq" ] && minimum_frequency; } ||
    { [ -n "$maxfreq" ] && maximum_frequency; } ||
    { menu; } 
}

menu() {
    cmd="$(printf 'governor\nminimum frequency\nmaximum frequency' | dmenu -i -p 'DCPU')"

    { [ "$cmd" = "governor" ] && governor; } ||
    { [ "$cmd" = "minimum frequency" ] && minimum_frequency; } ||
    { [ "$cmd" = "maximum frequency" ] && maximum_frequency; }
}

governor() {
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors | tr ' ' '\n' | grep -v '^[[:space:]]*$' | dmenu -p "governor" | xargs -I {} doas-askpass cpu --governor "{}"
}

minimum_frequency() {
    printf "400000\\n800000\\n1200000\\n1600000\\n2000000\\n2400000\\n2800000\\n3200000" | dmenu -i -p "minimum frequency" | xargs -I {} doas-askpass cpu --minfreq "{}"
}

maximum_frequency() {
    printf "400000\\n800000\\n1200000\\n1600000\\n2000000\\n2400000\\n2800000\\n3200000" | dmenu -i -p "maximum frequency" | xargs -I {} doas-askpass cpu --maxfreq "{}"
}

help() {
    printf "Usage:	dcpu [option]

Options:
 -g|--governor │ Manage governor
-fl|--minfreq  │ Manage minimum frequency
-fh|--maxfreq  │ Manage maximum frequency
 -h|--help     │ Print this help message and exit
When no arguments are supplied, the default menu will be used.
\n"
}

parse_opts() {
    while [ $# -gt 0 ]; do
        key="$1"
        case $key in
        -h|--help)
            help=1
            shift
            ;;
	-g|--governor)
	    governor=1
	    shift
	    ;;
	-fl|--minfreq)
	    minfreq=1
	    shift
	    ;;
	-fh|--maxfreq)
	    maxfreq=1
	    shift
	    ;;
	*)
	    shift
	    ;;
	esac
    done
}

main "$@"
