#!/bin/sh

governor() {
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors | tr ' ' '\n' | grep -v '^[[:space:]]*$' | dmenu -p "governor" | xargs -I {} doas-askpass cpu --governor "{}"
}

minimum_frequency() {
    printf "400000\\n800000\\n1200000\\n1600000\\n2000000\\n2400000\\n2800000\\n3200000" | dmenu -i -p "minimum frequency" | xargs -I {} doas-askpass cpu --minfreq "{}"
}

maximum_frequency() {
    printf "400000\\n800000\\n1200000\\n1600000\\n2000000\\n2400000\\n2800000\\n3200000" | dmenu -i -p "maximum frequency" | xargs -I {} doas-askpass cpu --maxfreq "{}"
}

if [ -n "$1" ]; then
    $1
else
    cmd="$(printf 'governor\nminimum frequency\nmaximum frequency' | dmenu -i -l 10 -p 'DCPU')"

    if [ "$cmd" = "governor" ]; then 
	governor
    elif [ "$cmd" = "minimum frequency" ]; then
	minimum_frequency
    elif [ "$cmd" = "maximum frequency" ]; then
	maximum_frequency
    fi
fi
